shop/app/main/__init__.py
# This bluepint will deal with all user management functionality

from flask import Blueprint

main_blueprint = Blueprint('main', __name__, template_folder='templates')

from . import views

shop/app/main/tasks/__init__.py
from .tasks import synchronize_orders

shop/app/main/views.py
import json
from functools import wraps
from random import randint

from flask import render_template, make_response, request, redirect, url_for, flash, abort
from flask_login import login_required, current_user

from db import db
from . import main_blueprint
from .tasks import synchronize_orders
from ..models import Book, Author, Order, books_orders_table
from ..utils.extensions import cache, csrf



# def is_owner(func):
#     @wraps(func)
#     def wrapper(id):
#         if Order.query.filter(Order.id == id).first().user_id == current_user.id:
#             func()
#         else:
#             abort(403)
#     return wrapper

def get_basket(r, additional=None):
    if r.cookies.get('basket'):
        basket = json.loads(r.cookies.get('basket'))
    else:
        basket = []
    if additional:
        basket.append(additional)
    books = Book.query.filter(Book.id.in_(basket), Book.count != 0).all()
    return books


def get_basket_rm(r, rm):
    basket = json.loads(r.cookies.get('basket'))
    basket.remove(rm)
    books = Book.query.filter(Book.id.in_(basket), Book.count != 0).all()
    return books


@main_blueprint.route('/')
def index():  # put application's code here
    page = request.args.get('page', 1, type=int)
    books_paginated = Book.query.filter(Book.count != 0).order_by(Book.id.desc()).paginate(page=page, per_page=9)
    carved_books, last_books_ids = [], []
    books = Book.query.filter(Book.count != 0).order_by(Book.id.desc()).all()

    if len(Book.query.filter(Book.count > 0).all()) >= 10:
        while len(carved_books) < 3 or len(carved_books) != len(books):
            book = books[randint(0, len(Book.query.all()) - 1)]
            if book not in carved_books:
                carved_books.append(book)

    if cache.get('last_books_ids'):
        last_books_ids = cache.get('last_books_ids')
    else:
        if len(books) % 3 == 1 or len(books) % 3 == 2:
            if len(books) % 3 == 1:
                last_books_ids.append(books[-1].id)
            else:
                last_books_ids.append(books[-1].id)
                last_books_ids.append(books[-2].id)

    return render_template('main/book_list.html',
                           books=books_paginated,
                           carved_books=carved_books,
                           last_books_ids=last_books_ids,
                           basket=get_basket(request))


@main_blueprint.route('/authors')
def authors_list():
    # cache.set("authors", Author.query.all())
    page = request.args.get('page', 1, type=int)
    authors = Author.query.filter().order_by(Author.id.desc()).paginate(page=page, per_page=10)
    return render_template('main/author_list.html', authors=authors, basket=get_basket(request))


@main_blueprint.route('/<string:isbn>')
def book_detail(isbn):
    return render_template('main/book_detail.html',
                           book=Book.query.filter(Book.isbn == isbn).first(),
                           basket=get_basket(request))


@main_blueprint.route('/author/<string:author_name>')
def author_detail(author_name):
    if '_' in author_name:
        return render_template(
            'main/author_detail.html',
            author=Author.query.filter(
                Author.first_name == author_name[:author_name.rfind('_')],
                Author.last_name == author_name[author_name.rfind('_') + 1:]).first(),
            basket=get_basket(request))
    else:
        return render_template(
            'main/author_detail.html',
            author=Author.query.filter(
                Author.first_name == author_name).first(),
            basket=get_basket(request))


@main_blueprint.route('/add_to_basket', methods=['post'])
@csrf.exempt
@login_required
def add_to_basket():
    data = dict()
    item = int(request.form.get("item"))
    basket = []
    if request.cookies.get('basket'):
        basket = json.loads(request.cookies.get('basket'))
        if item not in basket:
            basket.append(item)
        cookie = json.dumps(basket)
    else:
        cookie = json.dumps([item])
    if len(basket) > 1:
        cookie.replace(',', '\054')
    price = 0
    if request.cookies.get('basket'):
        books_cookie = json.loads(request.cookies.get('basket'))
        books_cookie.append(item)
    else:
        books_cookie = [item]
    order_books = Book.query.filter(Book.id.in_(books_cookie)).all()
    for book in order_books:
        price += book.price
    data['updated_basket'] = cookie
    data['html_basket_button'] = render_template('markup_components/basket.html', basket=get_basket(request, item))
    data['html_basket_form'] = render_template('main/forms/basket_form.html', basket=get_basket(request, item), price=round(price, 2))
    return data


@main_blueprint.route('/delete_book_basket', methods=['post'])
@csrf.exempt
@login_required
def delete_book_basket():
    data = dict()
    item = int(request.args.get("item"))
    basket = json.loads(request.cookies.get('basket'))
    if item in basket:
        basket.remove(item)
    cookie = json.dumps(basket)
    if len(basket) > 1:
        cookie.replace(',', '\054')
    price = 0
    books_cookie = json.loads(request.cookies.get('basket'))
    if books_cookie:
        order_books = Book.query.filter(Book.id.in_(books_cookie)).all()
        for book in order_books:
            price += book.price
    data['updated_basket'] = cookie
    data['html_basket_button'] = render_template('markup_components/basket.html', basket=get_basket_rm(request, item))
    data['html_basket_form'] = render_template('main/forms/basket_form.html', basket=get_basket_rm(request, item),
                                               price=round(price, 2))
    return data


@main_blueprint.route('/pay_order', methods=['get', 'post'])
@csrf.exempt
@login_required
def pay_order():
    data = dict()
    books_cookie = json.loads(request.cookies.get('basket'))
    order_books = Book.query.filter(Book.id.in_(books_cookie)).all()

    if request.method == "POST":
        form = request.form.to_dict()
        order = Order(
            price=request.form.get('price'),
            paid=True,
            user_id=current_user.id)

        try:
            db.session.add(order)
            db.session.commit()
            flash(f'Successfully payed order:{order.id}', 'success')
        except:
            flash('Error on order payment', 'danger')

        for key, value in form.items():
            if key != 'price' and int(value) != 0:
                book_order = books_orders_table.insert().values(**{
                    "book_id": int(key),
                    "order_id": int(order.id),
                    "count": int(value)
                })
                book = Book.query.filter(Book.id == key).first()
                book.count -= int(value)
                try:
                    db.session.execute(book_order)
                    db.session.commit()
                    print(f"book_id: {key}, order_id: {order.id}, count: {value} -> INSERT SUCCESS")
                except:
                    print(f"book_id: {key}, order_id: {order.id}, count: {value} -> INSERT ERROR")
        resp = make_response(redirect(url_for('main.index')))
        resp.delete_cookie("basket")
        return resp

    else:
        price = 0
        for book in order_books:
            price += book.price
        data['html_form'] = render_template('main/forms/basket_form.html', basket=get_basket(request), price=round(price, 2))
        return data


@main_blueprint.route('/order_detail/<int:id>')
@login_required
def order_detail(id):
    return {'hrml_order': render_template('main/components/order_detail_block.html', order=Order.query.filter(Order.id == id).first())}


@main_blueprint.route('/filter')
def books_filter():
    data = dict()
    books = Book.query.filter(Book.title.ilike(f"%{request.args.get('sub_string')}%")).all()
    # data['test'] = '' if not request.args.get('sub_string') else books[0].title
    max = len(books) if len(books) < 5 else 5
    data['html_filtered_books'] = render_template('main/components/filtered_books_block.html', books=books[:max])
    return data

shop/app/main/templates/main/author_detail.html
{% extends 'base.html' %}
{% block title %}
    {{ author }}
{% endblock %}
{% block content %}
    {% include 'main/components/author_detail_component.html' %}
{% endblock %}

shop/app/main/templates/main/author_list.html
{% extends 'base.html' %}
{% from "macros/_pagination_macros.html" import paginate %}

{% block title %}
    Author List
{% endblock %}
{% block content %}
    {% for author in authors.items %}
        {% include 'main/components/author_intro_component.html' %}
    {% endfor %}
    {{ paginate(authors) }}
{% endblock %}

shop/app/main/templates/main/book_detail.html
{% extends 'base.html' %}
{% block title %}
    {{ book.title }}
{% endblock %}
{% block content %}
    {% include 'main/components/book_detail_component.html' %}
{% endblock %}

shop/app/main/templates/main/book_list.html
{% extends 'base.html' %}
{% from "macros/_pagination_macros.html" import paginate %}

{% block title %}
    Index Page
{% endblock %}
{% block content %}
    {% if carved_books %}
        {% include 'main/components/book_carousel.html' %}
    {% endif %}
    {% if books.items %}
        <div class="row mb-2 mt-1 d-flex justify-content-between flex-wrap">
            {% for book in books.items %}
                {% include 'main/components/book_intro_component.html' %}
            {% endfor %}
        </div>
    {% else %}
        <p>Oosp... Looks like it's empty yet</p>
    {% endif %}

    {% if books.pages > 1 %}
        {{ paginate(books) }}
    {% endif %}
{% endblock %}

shop/app/main/templates/main/components/author_detail_component.html
<div>
    <h3>{{ author }}</h3>
    <p>Date of birth: {{ author.date_of_birth }}</p>
    {% if author.date_of_death %}
        <p>Date of death: {{ author.day_of_death }}</p>
    {% endif %}
    {% if author.books %}
        <ul>
            {% for book in author.books %}
                <li><a href="{{ book.get_absolute_url() }}">{{ book }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p> Book list is empty</p>
    {% endif %}
</div>

shop/app/main/templates/main/components/author_intro_component.html
<div class="d-flex">
    <p><a href="{{ author.get_absolute_url() }}">{{ author }}</a></p>
    <p class="mx-3">Books count: {{ author.books|length() }}</p>
</div>

shop/app/main/templates/main/components/book_carousel.html
<div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2" class="active" aria-current="true"></button>
        <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3" class=""></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#21242800"></rect></svg>
        <div class="container">
            <div class="carousel-caption text-start">
                <strong class="d-inline-block mb-2">
                {% for author in carved_books[0].authors %}
                    <a href="{{ author.get_absolute_url() }}" class="text-{{ author.colored_name() }}">{{ author }}</a>
                {% endfor %}
                </strong>
                <a href="{{ carved_books[0].get_absolute_url() }}" class="text-decoration-none">
                    <h4 class="text-danger">{{ carved_books[0].title|truncate(55) }}</h4>
                    <p class="text-light">{{ carved_books[0].summary|truncate(65) }}</p>
                </a>
            </div>
        </div>
    </div>
    <div class="carousel-item active">
    <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#21242800"></rect></svg>
    <div class="container">
        <div class="carousel-caption">
            <strong class="d-inline-block mb-2">
            {% for author in carved_books[1].authors %}
                <a href="{{ author.get_absolute_url() }}" class="text-{{ author.colored_name() }}">{{ author }}</a>
            {% endfor %}
            </strong>
            <a href="{{ carved_books[1].get_absolute_url() }}" class="text-decoration-none">
                <h4 class="text-danger">{{ carved_books[1].title|truncate(55) }}</h4>
                <p class="text-light">{{ carved_books[1].summary|truncate(65) }}</p>
            </a>
        </div>
    </div>
</div>
<div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#21242800"></rect></svg>
        <div class="container">
            <div class="carousel-caption text-end">
                <strong class="d-inline-block mb-2">
                {% for author in carved_books[2].authors %}
                    <a href="{{ author.get_absolute_url() }}" class="text-{{ author.colored_name() }}">{{ author }}</a>
                {% endfor %}
                </strong>
                <a href="{{ carved_books[2].get_absolute_url() }}" class="text-decoration-none">
                    <h4 class="text-danger">{{ carved_books[2].title|truncate(55) }}</h4>
                    <p class="text-light">{{ carved_books[2].summary|truncate(65) }}</p>
                </a>
            </div>
        </div>
    </div>
<button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
<span class="carousel-control-prev-icon" aria-hidden="true"></span>
<span class="visually-hidden">Previous</span>
</button>
<button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
<span class="carousel-control-next-icon" aria-hidden="true"></span>
<span class="visually-hidden">Next</span>
</button>
</div>
</div>

shop/app/main/templates/main/components/book_detail_component.html
<div class="book-detail">
    <h3>{{ book.title }}</h3>
    <p>ISBN: {{ book.isbn }}</p>
    <p>Price: {{ book.price }}</p>
    <div class="basket-button" data-url="{{ url_for("main.add_to_basket", id=book.id) }}">
                    <form class="add-to-basket" action="{{ url_for('main.add_to_basket') }}?next={{ url_for('main.book_detail', isbn=book.isbn) }}" method="POST">
                        <input type="hidden" value="{{ csrf_token }}">
                        <input type="hidden" name="item" value="{{ book.id }}">
                        <button class="btn btn-warning mt-3" style="width: auto;!important; height: auto;!important;" type="submit">Add to basket</button>
                    </form>
                </div>
    <ul>
        {% for author in book.authors %}
            <li class="d-flex justify-content-center"><a href="{{ author.get_absolute_url() }}">{{ author }}</a></li>
        {% endfor %}
    </ul>
    <p>{{ book.summary }}</p>
</div>

shop/app/main/templates/main/components/book_intro_component.html
<div class="col-md-{% if book.id in last_books_ids %}{% if last_books_ids|length == 1 %}12{% else %}6{% endif %}{% else %}4{% endif %}">
    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
            <h3 class="mb-0">{{ book.title|truncate(23) }}</h3>
            <p class="card-text mb-auto">{{ book.summary|truncate(32) }}</p>
            <div class="d-flex justify-content-around read-more-basket">
                <a href="{{ book.get_absolute_url() }}" class="center">
                    <button class="btn btn-info mt-3">read more</button>
                </a>
                <div class="basket-button" data-url="{{ url_for("main.add_to_basket", id=book.id) }}">
                    <form class="add-to-basket" action="{{ url_for('main.add_to_basket') }}?next={{ url_for('main.index') }}" method="POST">
                        <input type="hidden" value="{{ csrf_token }}">
                        <input type="hidden" name="item" value="{{ book.id }}">
                        <button class="btn btn-success mt-3" type="submit"><img src="{{ url_for('static', filename='img/basket_48.png') }}" alt=""></button>
                    </form>
                </div>
{#                <div class="basket-button add-to-basket">#}
{#                        <button class="btn btn-success mt-3" type="button" value="{{ book.id }}"><img src="{{ url_for('static', filename='img/basket_48.png') }}" alt=""></button>#}
{#                </div>#}
            </div>
        </div>
        <div class="col-auto d-none d-lg-block">
            <img src="" alt="">
        </div>
    </div>
</div>

shop/app/main/templates/main/components/filtered_books_block.html
<div class="container">
    <ul>
        {% for book in books %}
            <li><a href="{{ book.get_absolute_url() }}">{{ book.title }}</a></li>
        {% endfor %}
    </ul>
</div>

shop/app/main/templates/main/components/order_detail_block.html
<div class="bg-info">
    <h4>id: {{ order.id }}</h4>
    <p>date: {{ order.order_date }}</p>
    <ul>
        <h5>Books:</h5>
            {% for book in order.books %}
                <li>{{ book.title }}</li>
            {% endfor %}
    </ul>
</div>

shop/app/main/templates/main/forms/basket_form.html
    <div class="basket-form">
<div class=" d-flex justify-content-between m-3">
    <h4>Offers list</h4>
    <button class="btn btn-warning exit-button">Close</button>
</div>
<hr>
<form action="{{ url_for('main.pay_order') }}" method="POST" class="pay-order-form" id="pay-order-form">
    <input type="hidden" value="{{ csrf_token }}">

    <div class="shopping-cart-content order-book-list">
        {% for order_book in basket %}
            <div class="">
                <div class="row d-flex justify-content-around shopping-cart-input">
                    <label for="{{ order_book.id }}">{{ order_book.title|truncate(32) }}</label>
                    <div class="calc d-flex">
                        <input type="number" name="{{ order_book.id }}" id="{{ order_book.id }}" value="1" class="books-count" min="0" max="{{ order_book.count }}">
                        <p class="mx-1"> x </p>
                        <p>{{ order_book.price }}</p>
                        <p class="mx-1"> = </p>
                        <p class="one-book-summ">{{ order_book.price }}</p>
                    </div>
                    <div class="delete_book">
                        <form class="remove-from-basket" action="{{ url_for('main.delete_book_basket') }}?item={{ order_book.id }}" method="POST" id="delete-book">
                            <input type="hidden" value="{{ csrf_token }}" form="delete-book">
                            <input type="hidden" name="item" value="{{ order_book.id }}" form="delete-book">
                            <button class="btn btn-danger" type="submit" form="delete-book">x</button>
                        </form>
                    </div>
                </div>
            </div>
        {% endfor %}

    </div>
    <hr>
    <div class="d-flex justify-content-center"><p class="w-25">Price: </p><p class="calculated-price w-25">{{ price }}</p></div>

    <hr>
    <div class="d-flex justify-content-around mb-4">
{#        <form action="{{ url_for('main.clear_basket') }}?next={{ url_for('main.index') }}" method="POST">#}
{#            <input type="hidden" value="{{ csrf_token }}">#}
            <button class="btn btn-danger clear-basket" type="button">Clear basket</button>
{#        </form>#}
            <button class="btn btn-info" type="submit" form="pay-order-form">Offer</button>
    </div>
    <input type="hidden" value="{{ price }}" name="price" id="price" form="pay-order-form">

</form>
</div>